### ISSUE TITLE
BUG: Crash Opening Item Edit

### ISSUE THREAD

**Issue by mattwandcow** [Lightman314/LightmansCurrency#139] opened 2023-08-06 04:02 UTC
### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Lightman's Currency Version

lightmanscurrency-1.20.1-2.1.2.2c.jar

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When trying to set the price for a vending machine, and my client crashes with " mouseClicked event handler java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "io.github.lightman314.lightmanscurrency.client.gui.widget.ItemEditWidget.preFilteredItems" is null"

being the primary error.

When trying to replicate the issue by isolating the mod, it worked fine, then worked fine in the modpack in single player, then even worked fine on the server for a while when setting up the shop, but after a few hours doing other things, trying to set up vending machines started crashing me again

### To Reproduce

Place vending machine
Access GUI
click on "Set Price" for one of the vending machine slots.

### Screenshots/Logs/Crash Reports

[crash-2023-08-05_21.57.44-client.txt](https://github.com/Lightman314/LightmansCurrency/files/12268675/crash-2023-08-05_21.57.44-client.txt)

**Comment by Lightman314** [comment] 2023-08-07 16:28
Could you please provide the latest.log file (found in your installations `logs` folder) so that I can see what error is causing the item edit list to not initialize.

I can fix the crash regardless, but without the logs, I cannot tell what is actually causing the issue, and possible report the issue to the creator of the modded item/tab that's initializing incorrectly.

**Comment by mattwandcow** [comment] 2023-08-07 16:58
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/12283239/latest.log)

**Comment by Lightman314** [comment] 2023-08-07 17:09
It appears that the error is caused by a "rocks" mod not having an item registered properly...

`[06Aug2023 11:36:30.591] [Render thread/ERROR] [io.github.lightman314.lightmanscurrency.LightmansCurrency/]: Error encountered while setting up the Item Edit list.
Please report this error to the relevant mod author (if another mod is mentioned in the error), not to the Lightman's Currency Dev!
java.lang.NullPointerException: Registry Object not present: rocks:rock
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.20.1-47.1.3-universal.jar%23733!/:?]
	at eu.midnightdust.motschen.rocks.registry.RocksRegistry.lambda$static$62(RocksRegistry.java:103) ~[ThisRocks-1.20.1-1.5.1.jar%23696!/:1.5.1]`

Either way, I'll still fix error like these from crashing the mod entirely, but I sadly cannot prevent them from making the Item Edit widget fail to collect the item list.

**Comment by Lightman314** [comment] 2023-08-19 22:47
Fixed in v2.1.2.3

**Closed by Lightman314** 2023-08-19 22:47 UTC
Labels: bug
