### ISSUE TITLE
BUG: JEI Tooltips Don't Load

### ISSUE THREAD

**Issue by Schoperation** [Lightman314/LightmansCurrency#186] opened 2024-02-07 02:15 UTC
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Lightman's Currency Version

2.2.0.2

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Just Enough Items (15.3.0.1)

### Describe the bug

Hello, after updating my modpack to 1.20.1, I noticed that my inventory would take a little while (5 seconds) to load initially. After which, I'd see that the JEI tooltips are no longer loading, as seen in the screenshot. Looking in the logs, I saw Lightman's Currency as part of a thrown exception when JEI loads the tooltips. Upon removing Lightman's Currency, I no longer saw the error and the issue fixed itself.

In latest.log, search for `oak_log` and you can find what I'm talking about. There's a bunch of warnings about creative tabs from Zeta but I don't think those are relevant.

### To Reproduce

1. Log onto a singleplayer or multiplayer world (I see it happening on both), with at least Lightman's Currency and JEI
2. Open inventory
3. JEI tooltips on the block selection should display an error

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/14188052/latest.log)
[debug.log](https://github.com/Lightman314/LightmansCurrency/files/14188059/debug.log)
![2024-02-06_21 03 24](https://github.com/Lightman314/LightmansCurrency/assets/18017369/5a647bfb-5c44-472e-a4c8-faea4e961676)

**Comment by Lightman314** [comment] 2024-02-07 03:21
Noted. Issue will be fixed soon, although I'm curious how I didn't get this issue in my dev world as it also has JEI (great way to make sure the recipes are working as intended).

**Comment by Lightman314** [comment] 2024-02-08 04:02
Fixed in 2.2.0.3

**Closed by Lightman314** 2024-02-08 04:02 UTC

**Comment by Schoperation** [comment] 2024-02-08 04:39
Awesome, it's working now. Thank you very much
