### ISSUE TITLE
Mod causes Launcher Overlay to not disappear when joining game

### ISSUE THREAD

**Issue by OhNoScorpio** [Lightman314/LightmansCurrency#119] opened 2023-03-17 14:54 UTC
### Minecraft Version

1.19.3

### Forge Version

44.1.23

### Lightman's Currency Version

1.19.3-2.1.0.0.

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When adding the mod to the server and player folders, the "Launching the game"-overlay from the Launcher never goes away, rendering the server unplayable. Basically, you can join the server, but you're stuck in a weird limbo between Launcher and game, you cannot move or press any other buttons and your screen is slightly blacked out with "Launching the game" on top.

### To Reproduce

1. Insert the file into mod folder and server mod folder
2. launch the game with the corresponding version
3. join a modded server

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/11002603/latest.log)

**Comment by Lightman314** [comment] 2023-03-17 15:41
Unable to replicate. Likely caused by an issue with Biomes o' Plenty as noted in line 208 of your log:
`java.lang.NullPointerException: Registry Object not present: biomesoplenty:white_sand
	at java.util.Objects.requireNonNull(Objects.java:334) ~[?:?]
	at net.minecraftforge.registries.RegistryObject.get(RegistryObject.java:204) ~[forge-1.19.3-44.1.23-universal.jar%23177!/:?]
	at biomesoplenty.core.BiomesOPlenty.lambda$registerTab$2(BiomesOPlenty.java:157) ~[BiomesOPlenty-1.19.3-17.2.0.536.jar%23161!/:17.2.0.536]`
	
There appears to be an error in their code when it comes to registering their items to their creative mode tabs, which breaks my Item Edit initialization, as it requires an up-to-date Creative Tab item lists in order to collect a list of valid items.

I'll add in an error check to keep this from crashing the player login event, but this error will still persist unless BiomesOPlenty fixes their code, and said error will likely break their creative tabs as well as my Item Edit functionality.

**Comment by OhNoScorpio** [comment] 2023-03-17 15:57
Thank you so much for the quick response!! I'll check in with Biomes o' Plenty.

**Comment by Lightman314** [comment] 2023-03-17 21:55
The side-effect of the error where it locks you up unable to join the server should be fixed in v2.1.0.1

**Closed by Lightman314** 2023-03-17 21:55 UTC
Labels: bug
