### ISSUE TITLE
BUG: Ancient Sapling In Nature's Aura Not Growing

### ISSUE THREAD

**Issue by SnowiiPuractoii** [Lightman314/LightmansCurrency#251] opened 2024-09-30 10:52 UTC
### Minecraft Version

1.20.1

### Forge Version

47.2.18

### Lightman's Currency Version

2.2.2.1a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Nature's Aura 39.4

### Describe the bug

I'm playing with craft to exile 2, and when I plant a ancient sapling and use bonemeal on it, it won't grow.
In the console I found something when I use the bonemeal on sapling. It looks like the growing event goes wrong.

### To Reproduce

1.Place a ancient sapling
2.Use bonemeal on it

### Screenshots/Logs/Crash Reports

[309月2024 17:43:33.612] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.core.Holder.get()" because the return value of "net.minecraftforge.event.level.SaplingGrowTreeEvent.getFeature()" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class io.github.lightman314.lightmanscurrency.common.EventHandler treeGrowEvent(Lnet/minecraftforge/event/level/SaplingGrowTreeEvent;)V
		2: ASM: Block{minecraft:air} onTreeGrow(Lnet/minecraftforge/event/level/SaplingGrowTreeEvent;)V
		3: ASM: Block{minecraft:air} onTreeGrow(Lnet/minecraftforge/event/level/SaplingGrowTreeEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.get()" because the return value of "net.minecraftforge.event.level.SaplingGrowTreeEvent.getFeature()" is null
	at TRANSFORMER/lightmanscurrency@1.20.1-2.2.2.1a/io.github.lightman314.lightmanscurrency.common.EventHandler.treeGrowEvent(EventHandler.java:411)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.2.2.1a/io.github.lightman314.lightmanscurrency.common.__EventHandler_treeGrowEvent_SaplingGrowTreeEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.event.ForgeEventFactory.blockGrowFeature(ForgeEventFactory.java:738)
	at TRANSFORMER/naturesaura@39.4/de.ellpeck.naturesaura.blocks.BlockAncientSapling.m_214148_(BlockAncientSapling.java:77)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:73)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BoneMealItem.m_6225_(BoneMealItem.java:36)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:358)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[309月2024 17:43:33.614] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@fc0ec22, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.get()" because the return value of "net.minecraftforge.event.level.SaplingGrowTreeEvent.getFeature()" is null
	at io.github.lightman314.lightmanscurrency.common.EventHandler.treeGrowEvent(EventHandler.java:411) ~[lightmanscurrency-1.20.1-2.2.2.1a.jar%23506!/:1.20.1-2.2.2.1a]
	at io.github.lightman314.lightmanscurrency.common.__EventHandler_treeGrowEvent_SaplingGrowTreeEvent.invoke(.dynamic) ~[lightmanscurrency-1.20.1-2.2.2.1a.jar%23506!/:1.20.1-2.2.2.1a]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.event.ForgeEventFactory.blockGrowFeature(ForgeEventFactory.java:738) ~[forge-1.20.1-47.2.18-universal.jar%23634!/:?]
	at de.ellpeck.naturesaura.blocks.BlockAncientSapling.m_214148_(BlockAncientSapling.java:77) ~[NaturesAura-39.4.jar%23527!/:39.4]
	at net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:73) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.world.item.BoneMealItem.m_6225_(BoneMealItem.java:36) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.20.1-47.2.18-universal.jar%23634!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:358) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[309月2024 17:43:33.818] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.core.Holder.get()" because the return value of "net.minecraftforge.event.level.SaplingGrowTreeEvent.getFeature()" is null
	Index: 1
	Listeners:
		0: NORMAL
		1: ASM: class io.github.lightman314.lightmanscurrency.common.EventHandler treeGrowEvent(Lnet/minecraftforge/event/level/SaplingGrowTreeEvent;)V
		2: ASM: Block{minecraft:air} onTreeGrow(Lnet/minecraftforge/event/level/SaplingGrowTreeEvent;)V
		3: ASM: Block{minecraft:air} onTreeGrow(Lnet/minecraftforge/event/level/SaplingGrowTreeEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.get()" because the return value of "net.minecraftforge.event.level.SaplingGrowTreeEvent.getFeature()" is null
	at TRANSFORMER/lightmanscurrency@1.20.1-2.2.2.1a/io.github.lightman314.lightmanscurrency.common.EventHandler.treeGrowEvent(EventHandler.java:411)
	at TRANSFORMER/lightmanscurrency@1.20.1-2.2.2.1a/io.github.lightman314.lightmanscurrency.common.__EventHandler_treeGrowEvent_SaplingGrowTreeEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.event.ForgeEventFactory.blockGrowFeature(ForgeEventFactory.java:738)
	at TRANSFORMER/naturesaura@39.4/de.ellpeck.naturesaura.blocks.BlockAncientSapling.m_214148_(BlockAncientSapling.java:77)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:73)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.BoneMealItem.m_6225_(BoneMealItem.java:36)
	at TRANSFORMER/forge@47.2.18/net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:358)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.TickTask.run(TickTask.java:18)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1583)

[309月2024 17:43:33.820] [Server thread/ERROR] [net.minecraft.network.protocol.PacketUtils/]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@7a635a66, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.core.Holder.get()" because the return value of "net.minecraftforge.event.level.SaplingGrowTreeEvent.getFeature()" is null
	at io.github.lightman314.lightmanscurrency.common.EventHandler.treeGrowEvent(EventHandler.java:411) ~[lightmanscurrency-1.20.1-2.2.2.1a.jar%23506!/:1.20.1-2.2.2.1a]
	at io.github.lightman314.lightmanscurrency.common.__EventHandler_treeGrowEvent_SaplingGrowTreeEvent.invoke(.dynamic) ~[lightmanscurrency-1.20.1-2.2.2.1a.jar%23506!/:1.20.1-2.2.2.1a]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?]
	at net.minecraftforge.event.ForgeEventFactory.blockGrowFeature(ForgeEventFactory.java:738) ~[forge-1.20.1-47.2.18-universal.jar%23634!/:?]
	at de.ellpeck.naturesaura.blocks.BlockAncientSapling.m_214148_(BlockAncientSapling.java:77) ~[NaturesAura-39.4.jar%23527!/:39.4]
	at net.minecraft.world.item.BoneMealItem.applyBonemeal(BoneMealItem.java:73) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.world.item.BoneMealItem.m_6225_(BoneMealItem.java:36) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:585) ~[forge-1.20.1-47.2.18-universal.jar%23634!/:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:245) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:358) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:139) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:733) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23629!/:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Lightman314** [comment] 2024-09-30 16:58
Duplicate of #235

As noted in that issue, this has been fixed since LC v2.2.2.4.

Please always update to the latest version of my mod to see if your issue has been fixed before reporting an issue.

**Closed by Lightman314** 2024-09-30 16:58 UTC
Labels: Bug
