### ISSUE TITLE
Members of LAN server become disconnected

### ISSUE THREAD

**Issue by Chromeyay** [Lightman314/LightmansCurrency#14] opened 2021-12-31 22:46 UTC
Sorry for the second issue in the last 24 hours but people on my LAN server keep timing out for this error. Not sure if this is connected to the mod but it didn't happen before.

The old issue seems to be resolved

![image](https://user-images.githubusercontent.com/82741859/147840516-84edc583-b319-46ae-9f45-0517db3dc895.png)
![image](https://user-images.githubusercontent.com/82741859/147840519-778bff93-d490-4810-9ea3-7de6f943d785.png)

**Comment by Lightman314** [comment] 2021-12-31 23:05
I can't imagine how this would happen. Could you please provide the logs from those involved (including the one who's hosting the lan server), so that I can see why they're being disconnected?

**Comment by Chromeyay** [comment] 2021-12-31 23:45
There's no available crash report because I'm hosting it on my PC. I am not crashing but they are for some reason.

**Comment by Lightman314** [comment] 2021-12-31 23:47
There are logs other than crash reports... Just go the the logs folder and post the lastest.log (or the dated *.log.gz file that problem occurred in).

**Comment by Chromeyay** [comment] 2021-12-31 23:48
[debug-3.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797223/debug-3.log.gz)
[debug-4.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797224/debug-4.log.gz)
[debug-5.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797225/debug-5.log.gz)
[debug-1.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797226/debug-1.log.gz)

Not sure if these are the right ones but here they are
[debug-2.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797227/debug-2.log.gz)

**Comment by Lightman314** [comment] 2022-01-01 00:06
Sadly, none of those seem to be useful. As I said previously (although you posted these before I got the edit off), if they're crashing only their crash log or latest.log would help. Also, make sure that they've updated their Lightman's Currency version such that the crash from the previous issue is fixed on their end as well.

**Comment by Chromeyay** [comment] 2022-01-01 00:08
Unfortunately I cant upload .log files to github, is there any other way to

**Comment by Lightman314** [comment] 2022-01-01 01:52
You could change the file extension to .txt instead of .log

**Comment by Chromeyay** [comment] 2022-01-01 03:18
[debug-2.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797332/debug-2.log.gz)
[debug-3.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797333/debug-3.log.gz)
[debug-4.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797334/debug-4.log.gz)
[debug-5.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7797335/debug-5.log.gz)
[debug.txt](https://github.com/Lightman314/LightmansCurrency/files/7797336/debug.txt)

These are the last few files I can actually upload, even after converting to txt it doesnt let me

**Comment by Lightman314** [comment] 2022-01-01 03:35
These log files are from when v1.0.1.5 was installed and refer to the previous issue. They also appear to be the exact same files you have already given me, as they're the exact same file size down to the byte.

If these are from your friends, **they** need to update their Lightman's Currency version (as I have requested you confirm that they have done so in my last 2 comments).

If they're from you then they are not helpful at all, as I have also stated in the last 2 comments that I need the crash reports from the people that are actually crashing to properly address the issue. Since your version is not encountering any issues,any logs from your computer/minecraft installation will only tell me that everything is working as intended.

**Comment by Chromeyay** [comment] 2022-01-01 21:47
[debug-5.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7798275/debug-5.log.gz)
[debug-4.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7798276/debug-4.log.gz)
[debug-3.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7798277/debug-3.log.gz)
[debug-2.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7798278/debug-2.log.gz)
[debug-1.log.gz](https://github.com/Lightman314/LightmansCurrency/files/7798279/debug-1.log.gz)
[debug.txt](https://github.com/Lightman314/LightmansCurrency/files/7798280/debug.txt)
[latest.txt](https://github.com/Lightman314/LightmansCurrency/files/7798281/latest.txt)

I was able to get it from one of my friends, here they are.

**Comment by HonzaVinCZ** [comment] 2022-01-02 16:40
Using lightmanscurrency-1.18-1.0.1.7 and I have no LAN problems with my friends. They can connect without any problems. The connection exception is sent just one or two times but that is very propably not mod related but its more likely my laptop is old and slow.

**Comment by Lightman314** [comment] 2022-01-02 18:02
These logs do not show any errors, nor any attempts to actually connect to a server. Considering that neither myself or Honza are having this issue, I'm going to assume this issue is caused by user error (either mismatching mod list, using an outdated version with known issues, or some other form of network issue unrelated to minecraft) and close the ticket.

**Closed by Lightman314** 2022-01-02 18:02 UTC
