### ISSUE TITLE
BUG: Corpse Mod conflict

### ISSUE THREAD

**Issue by K4N0** [Lightman314/LightmansCurrency#43] opened 2022-03-18 20:55 UTC
Minecraft Version (REQUIRED): 1.18.1
Forge Version (REQUIRED): forge-1.18.1-39.1.2
Lightman's Currency Version (REQUIRED): lightmanscurrency-1.18-1.0.5.3.jar
Corpse Version (REQUIRED): corpse-1.18.1-1.0.4.jar
Other Relevant Mods & Version (LC Tech, etc.): Modpack: https://www.curseforge.com/minecraft/modpacks/cataclysm-zombie-apocalypse
Connection Type (Single-player, server/client, LAN world): Modpack comes with a server IP

**Describe the bug**
I am attempting to keep the wallet from dropping when a player dies. I have enabled gamerule keepWallet. 
When a player dies, the wallet remains on the player in the wallet slot, but the coins are pulled out of it.
"Corpse" Mod Conflict
Corpse Mod: https://www.curseforge.com/minecraft/mc-mods/corpse

**To Reproduce**
1. Install both lightmans and corpse mod
2. enable gamerule keepwallet
3. die
4. wallet does not drop, but the coins get pulled out of the wallet

**Expected behavior**
It would be nice if the coins would stay in the wallet upon death.
I understand this may be an issue on their end and I have taken the liberty of creating an issue on their end as well.

**Screenshots/Logs/Crash Reports**
You can find your minecraft logs in the /logs folder (ideally the latest.log file if you've not launched your game again since the error happened, and/or crash report if a crash happened)

**Additional context**

**Comment by K4N0** [comment] 2022-03-18 20:55
https://github.com/henkelmax/corpse/issues/88

**Comment by Lightman314** [comment] 2022-03-18 21:05
Have you set the coinDropPercent gamerule to 100 or higher? Cause if that gamerule is set to 100(%), then the coins will drop from the wallet on death, and then be collected by the corpse mod as dropped item(s). By default it should be 0 though, so I'll look into it, though I do have one quick question. Are any items ever duplicated with this bug (is the wallet both left equipped, and placed in the corpse, etc.)

**Comment by Lightman314** [comment] 2022-06-14 20:32
Since you never got around to answering my questions, I finally got around to testing the corpse interaction with my mod, and I have not encountered your issue. When keepWallet is on, and coinDropPercent is 0, your wallet remains in the wallet slot instead of being placed in the corpse, and all of the coins (I used a stack of netherite for testing) remained inside of the wallet. When I changed the coinDropPercent rule to 10 (10%), the wallet remained in the wallet slot, and 6 netherite coins and 4 diamond coins were removed from the wallet and placed in the corpse.
From that test alone, the interactions seem to be working 100% as intended, and thus I will be closing this issue.

**Closed by Lightman314** 2022-06-14 20:32 UTC
Labels: bug, question
