### ISSUE TITLE
BUG: [1.19] Crash when coin sound triggered on server.

### ISSUE THREAD

**Issue by Zelioth** [Lightman314/LightmansCurrency#86] opened 2022-09-15 00:05 UTC
Minecraft Version (REQUIRED): 1.19.2
Forge Version (REQUIRED): 43.1.25
Lightman's Currency Version (REQUIRED): 1.2.0.7
Other Relevant Mods & Version (LC Tech, etc.): Mod Pack and Server Pack "Friends United" https://www.curseforge.com/minecraft/modpacks/friends-united

Connection Type (Single-player, server/client, LAN world): Server/Client
If playing on a server, was the server ever in Offline Mode: No

**Describe the bug**
When users on the server break coin stacks it kicks the player. Through testing I have found that it does it with all coin stacks I will post the error and disconnect in a text file directly from server console.

**To Reproduce**
1. Go to 'Currently I can not test other server, but join Friends United public server included in the pack'
2. 'Break any coil pile in game and it will kick player'
4. See error server side only. Client just states disconnected

**Expected behavior**
To not kick clients.

**Screenshots/Logs/Crash Reports**

[Lightmans Currecnt Disconnect.txt](https://github.com/Lightman314/LightmansCurrency/files/9570694/Lightmans.Currecnt.Disconnect.txt)

**Comment by Zelioth** [comment] 2022-09-15 00:12
This also showed up when it happened. This error was from the connect/disconnect log on our hoser

23:51:27 <>                       Player SlyKye disconnected (Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@19d6c389' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)])

**Comment by Lightman314** [comment] 2022-09-15 16:01
Huh. It would appear that sound events have a registry now? I'm not quite sure how that works, considering that resource packs can add more sounds without having to register them, but whatever I guess.
I should have this fixed in my next update, but that's probably going to be a while since I'm in the middle of a major re-work and I need to make sure it doesn't break everything (which means a lot of testing is going to be needed).

**Comment by Zelioth** [comment] 2022-09-18 23:11
So this is now extending to other aspects of the mod and making the game almost unplayable for some. it is not affecting everything but some players are killing mobs and getting this 

User HerbalFatCat has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.IllegalArgumentException: Can't find id for 'net.minecraft.sounds.SoundEvent@5ff354e1' in map Registry[ResourceKey[minecraft:root / minecraft:sound_event] (Experimental)]

the only mobs that crash these players are ones that are vanilla and drop coins when killed.

**Comment by Lightman314** [comment] 2022-09-18 23:21
It's likely caused by their wallet picking up the dropped coins and playing the coin clink sound. It should be fixed in the next build, but I cannot make any promises as to when it will be released as it's a major change that requires a **lot** of testing to make sure everything still works as intended.

**Comment by Zelioth** [comment] 2022-09-19 00:01
I think so to. is there a way you could just disable all sound events within the mod to stop the error until you do that testing? I mean i know it'll be weird but we don't need sounds. plus I really love using your mod. I don't wanna have to remove it till it's fixed kinda deal. 

also the new crash was caused by netherite wallet on both inventory and bobble bar

**Comment by Lightman314** [comment] 2022-09-20 18:25
Should be fixed in v2.0.0.0.

**Closed by Lightman314** 2022-09-20 18:25 UTC
Labels: bug, 1.19
