### ISSUE TITLE
BUG: Terraqueous causes game to not load

### ISSUE THREAD

**Issue by JuddJohnsonIV** [Lightman314/LightmansCurrency#229] opened 2024-06-03 05:35 UTC
### Minecraft Version

1.20.1

### Forge Version

47.2.32

### Lightman's Currency Version

2.2.1.3b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

LC tech 1.20.1-0.2.1.3c
waystones and lightmans 1.0.2-1.20.1

### Describe the bug

booting up i am greeted by this lovley error loading mod page 

### To Reproduce

I loaded these mods listed in the log and got this error on play button and waiting a bit

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/user-attachments/files/15529181/latest.log)
[crash-2024-06-02_22.26.32-fml.txt](https://github.com/user-attachments/files/15529182/crash-2024-06-02_22.26.32-fml.txt)
![error screen](https://github.com/Lightman314/LightmansCurrency/assets/117565290/6ebf942a-d32a-42f7-bedb-05342c41df94)

**Comment by JuddJohnsonIV** [comment] 2024-06-03 05:43
[removing terraqueos  mod](https://www.curseforge.com/minecraft/mc-mods/terraqueous) allows the game to load with no error

**Comment by Lightman314** [comment] 2024-06-03 16:39
Unfortunately Terraqueous is not open source and thus it is impossible for me to debug any potential conflicts I could have with their mod (Even when going to the code portion of their github page, all it has is language files, no actual code).

With that and the fact that the stack trace shows that the exception thrown is from adding a config file to a list, which is an action that should *never* end up throwing an `ArrayIndexOutOfBoundsException` (the documentation of the function does not list that as a valid exception that it can throw), all I can assume is that their mod is somehow making changes that are interfering with core java classes in ways that are causing conflicts.

**Comment by Lightman314** [comment] 2024-08-18 02:08
Looked into terraqueos, and it seems like the cause of the issue can be found here, and is not exclusive to my mod:

https://github.com/ShetiPhian/Localizations-and-Issues/issues/451

I'm going to officially close this issue as somehow they're breaking core java classes for no discernible reason.

**Closed by Lightman314** 2024-08-18 02:08 UTC
Labels: Bug, Other Mods Issue
