### ISSUE TITLE
BUG: Log Warn

### ISSUE THREAD

**Issue by Krimatoria** [Lightman314/LightmansCurrency#203] opened 2024-02-26 17:31 UTC
### Minecraft Version

1.19.2

### Forge Version

Forge 43.3.5

### Lightman's Currency Version

lightmanscurrency-1.19.2-2.2.1.0b.jar

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

zombieawareness-1.19.2-1.12.3.jar
aether-1.19.2-1.2.0-forge.jar
architectury-6.5.90-forge.jar
Atlas-Lib-1.19.2-1.1.6.jar
AutoRegLib-1.8.2-55.jar
BadOptimizations-1.6.3.jar
balm-forge-1.19.2-4.6.0.jar
biomancy-forge-1.19.2-2.3.2.0.jar
BOH_0.0.2.5.jar
born_in_chaos_[Forge]1.19.2_1.10.1.jar
catalogue-1.7.0-1.19.2.jar
citadel-2.1.4-1.19.jar
configured-2.1.1-1.19.2.jar
ConfiguredDefaults-v8.0.1-1.20.1-Forge.jar
Controlling-forge-1.19.2-10.0+7.jar
coroutil-forge-1.19.2-1.3.6.jar
cultofthewither2.4.jar
cumulus_menus-1.19.2-1.0.0-forge.jar
curios-forge-1.19.2-5.1.6.1.jar
Dangers in the Darkness_1.0.28_Forge_1.19.2.jar
darktimer-forge-1.19.2-1.1.5.jar
DistantFriends-1.19.2-0.2.3.jar
drippyloadingscreen_forge_2.2.2_MC_1.19.1-1.19.2.jar
embeddium-0.3.5+mc1.19.2.jar
embeddiumplus-1.19.2-v1.2.4.jar
emi-1.1.2+1.19.2+forge.jar
endofherobrine-1.19.2-1.0.7.1.jar
EnhancedAI-1.8.5-mc1.19.2.jar
entityculling-forge-1.6.1-mc1.19.2.jar
fancymenu_forge_2.14.13_MC_1.19-1.19.2.jar
FastFurnace-1.19.2-7.0.0.jar
Fastload-Reforged-mc1.19.2-3.4.0.jar
FastSuite-1.19.2-4.1.1.jar
FastWorkbench-1.19.2-7.1.4.jar
ferritecore-5.0.3-forge.jar
From-The-Fog-1.19-v1.9.1-Forge-Fabric.jar
geckolib-forge-1.19-3.1.40.jar
Icterine-forge-1.2.0.jar
ImmediatelyFast-Forge-1.2.10+1.19.2.jar
InsaneLib-1.7.5-mc1.19.2.jar
konkrete_forge_1.8.0_MC_1.19-1.19.2.jar
kotlinforforge-3.12.0-all.jar
kubejs-forge-1902.6.2-build.63.jar
L_Enders_Cataclysm-1.90 tongue fixed-1.19.2.jar
lazydfu-1.19-1.0.2.jar
lightmanscurrency-1.19.2-2.2.1.0b.jar
lootjs-forge-1.19.2-2.9.1.jar
MobCaptains-v2.1.2.jar
MobsPropertiesRandomness-4.2.3-mc1.19.2.jar
Monster Hunter Villager 1.1.0-1.19.2.jar
MutantMonsters-v4.0.6-1.19.2-Forge.jar
nerb-1.19.2-0.3-FORGE.jar
neruina-1.3.0-forge+1.18.2-1.20.1.jar
no_f3-1.0.jar
noisium-1.0.2.jar
observable-3.3.1.jar
Paxi-1.19.2-Forge-3.0.1.jar
Pehkui-3.7.11+1.19.2-forge.jar
Placebo-1.19.2-7.3.5.jar
PuzzlesLib-v4.4.3-1.19.2-Forge.jar
Quark-3.4-418.jar
Raided-1.19.2-0.1.4.jar
realmrpg_fallen_adventurers_1.0.3_forge_1.19.2.jar
redirector-5.0.0.jar
reforgium-1.0.12a.jar
RegionsUnexploredForge-0.5.3+1.19.2.jar
rhino-forge-1902.2.3-build.284.jar
rottencreatures-forge-1.19.2-1.0.1.jar
rubidium-extra-0.4.19+mc1.19.2-build.105.jar
sons-of-sins-1.19.2-2.1.5b.jar
sophisticatedbackpacks-1.19.2-3.20.1.1013.jar
sophisticatedcore-1.19.2-0.6.2.552.jar
spark-1.10.37-forge.jar
spore_1.19_2_2.0.2c.jar
superbosses-1.2.0-1.19.2.jar
Supernatural-2.6.5.jar
TenebrousLands_1.19.2.jar
teraphobia-2.0.0.jar
TerraBlender-forge-1.19.2-2.0.1.166.jar
Terralith_1.19.3_v2.3.12.jar
textrues_embeddium_options-0.1.1+mc1.19.2.jar
The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar
The_Graveyard_Biomes_1.4_(FORGE)_for_1.19.2.jar
thefallenmonstersprehistoricaupdate.jar
The-Hordes-1.19.2-1.2.3.jar
There is something in the caves_1.0.0.jar
UndeadUnleashed-1.1.1-1.19.2.jar
waystones-forge-1.19.2-11.4.2.jar
yeetusexperimentus-1.0.1-build.2+mc1.19.1.jar
YungsApi-1.19.2-Forge-3.8.10.jar
YungsBetterDesertTemples-1.19.2-Forge-2.2.2.jar
YungsBetterDungeons-1.19.2-Forge-3.2.2.jar
YungsBetterEndIsland-1.19.2-Forge-1.0.jar
YungsBetterJungleTemples-1.19.2-Forge-1.0.1.jar
YungsBetterMineshafts-1.19.2-Forge-3.2.1.jar
YungsBetterNetherFortresses-1.19.2-Forge-1.0.6.jar
YungsBetterOceanMonuments-1.19.2-Forge-2.1.1.jar
YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar
YungsBetterWitchHuts-1.19.2-Forge-2.1.0.jar
YungsBridges-1.19.2-Forge-3.1.0.jar

### Describe the bug

> [20:16:11] [Render thread/WARN] [io.gi.li.li.LightmansCurrency/]: ATM Icon Type 'lightmanscurrency:item' was registered twice.
> [20:16:11] [Render thread/WARN] [io.gi.li.li.LightmansCurrency/]: ATM Icon Type 'lightmanscurrency:small_arrow' was registered twice.
> [20:16:11] [Render thread/WARN] [io.gi.li.li.LightmansCurrency/]: ATM Icon Type 'lightmanscurrency:sprite' was registered twice.
> [20:17:41] [Render thread/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: lightmanscurrency:coin_chocolate_netherite Expected: 2243 Got: 1454

By the way, I stopped seeing chocolate coins after the update. By the way, I stopped seeing chocolate coins after the update. They used to fall from mobs. Then it stopped.

> [20:17:41] [Render thread/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: lightmanscurrency:trading_core Expected: 2244 Got: 1455
> [20:17:41] [Render thread/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: lightmanscurrency:ticket Expected: 2245 Got: 1456a

> [20:51:18] [Server thread/WARN] [minecraft/BlockEntity]: Skipping BlockEntity with id lightmanscurrency:item_trader
> [20:51:18] [Server thread/WARN] [minecraft/BlockEntity]: Skipping BlockEntity with id lightmanscurrency:item_trader

### To Reproduce

lightmanscurrency-1.19.2-2.2.1.0b.jar

### Screenshots/Logs/Crash Reports

[Skipping.txt](https://github.com/Lightman314/LightmansCurrency/files/14408246/Skipping.txt)
[Registered.txt](https://github.com/Lightman314/LightmansCurrency/files/14408250/Registered.txt)

**Comment by Lightman314** [comment] 2024-02-26 18:14
Partial duplicate of #200.
As mentioned both there, and in #202 where you also mentioned this, this "INFO" logs of `Skipping loading recipe...` are posted by forge whenever an optional recipe fails its prerequisites to load (in this case it requires another mod to be loaded so that the required wood type actually exists).

As for the `Object did not get ID it asked for. ` warnings, that's 100% forges internal registries doing things weird and you'd have to ask them what's going on with that. It's 100% out of my hands.

The `ATM Icon Type 'lightmanscurrency:item' was registered twice.` warning though is an oversight on my part and will be fixed in the next update, but for the time being it's irrelevant and can be ignored.

**Closed by Lightman314** 2024-02-26 18:14 UTC
Labels: Bug

**Comment by Krimatoria** [comment] 2024-02-26 18:28
> Partial duplicate of #200. As mentioned both there, and in #202 where you also mentioned this, this "INFO" logs of `Skipping loading recipe...` are posted by forge whenever an optional recipe fails its prerequisites to load (in this case it requires another mod to be loaded so that the required wood type actually exists).
> 
> As for the `Object did not get ID it asked for. ` warnings, that's 100% forges internal registries doing things weird and you'd have to ask them what's going on with that. It's 100% out of my hands.
> 
> The `ATM Icon Type 'lightmanscurrency:item' was registered twice.` warning though is an oversight on my part and will be fixed in the next update, but for the time being it's irrelevant and can be ignored.

I understand you) thank you) It's a pity I won't be able to find out which resource pack it is. To find out this error. As an example) how can I find out what kind of mod is doing strange things with a resource pack)

> [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: lightmanscurrency:wallet_iron Expected: 2250 Got: 1461
> [20:17:41] [Render thread/WARN] [ne.mi.re.ForgeRegistry/REGISTRIES]: Registry minecraft:item: Object did not get ID it asked for. Name: lightmanscurrency:coin_chest_magnet_upgrade_1 Expected: 2269 Got: 1480
>
