### ISSUE TITLE
BUG: Infinite "Joining World" issue when joining a dedicated server with 1.20.1-2.2.0.1b

### ISSUE THREAD

**Issue by dylanjkl** [Lightman314/LightmansCurrency#181] opened 2024-01-26 21:40 UTC
### Minecraft Version

1.20.1

### Forge Version

1.20.1-forge-47.1.96

### Lightman's Currency Version

1.20.1-2.2.0.1b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

N/A

### Describe the bug

Causes an inability to join a dedicated server.
Spent over an hour diagnosing mod by mod (after adding 4-5 mods) and found lightmans to be causing the issue/incompatibility - previous version of lightmans works, but this newest version causes the issue.

### To Reproduce

1. Join server with lightmans 1.20.1-2.2.0.1b installed on both client and server.
2. Joining World screen will be permanantely stuck on the screen.
3. Joining World screen background will be removed with just the text visible.

### Screenshots/Logs/Crash Reports

![joiningworld](https://github.com/Lightman314/LightmansCurrency/assets/25552125/cf926d1e-83f0-4ea6-98b9-bab643abf886)
[crash-2024-01-26_21.36.47-client.txt](https://github.com/Lightman314/LightmansCurrency/files/14069550/crash-2024-01-26_21.36.47-client.txt)

**Comment by Lightman314** [comment] 2024-01-26 21:43
Duplicate of #180, which has already been resolved in v2.2.0.1c.

**Closed by Lightman314** 2024-01-26 21:43 UTC
Labels: bug

**Comment by dylanjkl** [comment] 2024-01-26 22:00
Sorry I meant to put v2.2.0.1c, v2.2.0.1b is the version that actually works on the server, version C causes crashes.

**Comment by dylanjkl** [comment] 2024-01-26 22:01
I had to revert from version v2.2.0.1c to v2.2.0.1b in order for this bug to not occur.

**Comment by Lightman314** [comment] 2024-01-26 22:11
My apologies as well, as I got the wrong version on my comment. This was fixed in v2.2.0.1d, not c.
