### ISSUE TITLE
Issues found so far in Lightmans Currency 2.0.0.0

### ISSUE THREAD

**Issue by Zelioth** [Lightman314/LightmansCurrency#88] opened 2022-09-23 05:02 UTC
Minecraft Version (REQUIRED): 1.19.2
Forge Version (REQUIRED): 43.1.27
Lightman's Currency Version (REQUIRED):  2.0.0.0 Beta
Other Relevant Mods & Version (LC Tech, etc.): Custom Mod Pack / https://www.curseforge.com/minecraft/modpacks/friends-united
Connection Type (Single-player, server/client, LAN world): Server/Single-Player
If playing on a server, was the server ever in Offline Mode: No 

**Describe the bug**
So lets start with the Display Case : placing the item and going into Edit Trader's and Rules. For some reason the first time I did it it would not let me check mark anything. might of been server lag but unsure. it corrected after breaking the display case and replacing it. I'm finding that it's happening more often or if someone else access the machine to receive something out i can't select anything under that menu.  When applying free sample to items after giving the free sample it doesn't show the price after receiving the free sample. The display says "You have done this trade 0 of one time 1 time and even if money is in the slot it does not purchase another item. 
UPDATE * This issue seems to be linked to having Player trade limit on and Free Sample. I set it to 5 and it gives me 4 more swords ontop of the free sample while taking coins but still says 0 of 5 time within the last 1 day. 
for some reason they I can't access one of the display cases anymore. after crashing had to break it and replace remaking its contents. 
Pressing " Create A persistent Trader with a copy of this traders trades & names crashes my GUI of my client. Here is the Crashy: https://crashy.net/tIhdbNfqFxDkHoTAo4Ep

Is the "Name" function just a name for the trade or is it supposed to act like an anvil and name items. Would be cool in creative mode if it named the items people bought for custom server items. 

Vending Machine : Seems to be also affected by Settings Free Samples and Player Trade Limit. Settings will give players ONE Free item set but not show the price of that item after the free sample or change the "You have done this trade 0 of 5 Times" that shows up. The Vending machine also crashes when pushing the P button. Crashy Report : https://crashy.net/CxBmunw3q1dZ6GBLq6zO

If some of these issues aren't bugs or I am just doing something incorrect I apologize. 

**Screenshots/Logs/Crash Reports**
You can find your minecraft logs in the /logs folder (ideally the latest.log file if you've not launched your game again since the error happened, and/or crash report if a crash happened)

**Additional context**
[crash-2022-09-22_23.25.16-client.txt](https://github.com/Lightman314/LightmansCurrency/files/9630789/crash-2022-09-22_23.25.16-client.txt)
[crash-2022-09-22_23.51.15-client.txt](https://github.com/Lightman314/LightmansCurrency/files/9630791/crash-2022-09-22_23.51.15-client.txt)
![Lightmans Currency Free Samples](https://user-images.githubusercontent.com/77481431/191894921-4d3912b8-faba-4ca9-9d21-7970f31fe154.jpg)
![Lightmans Currecny Settings](https://user-images.githubusercontent.com/77481431/191894968-f0cf1a34-3ff8-4b8f-aa5b-cc84ebacbc6b.jpg)
![Done trade multiple times](https://user-images.githubusercontent.com/77481431/191895064-e7b28c63-c687-4453-886e-3ab145094f26.jpg)

**Comment by Zelioth** [comment] 2022-09-23 05:27
This vending machine was one I had placed before the update. it was working. I tested the free samples and player limit. after leaving the machine and trying to go back in it is bugged and will not let me click on it again to change any settings. Bricked pretty much. I placed another machine trying to recreate the "Brick" issue but for some reason I can't change any settings now. 

What I did. 
I turned the machine to creative
Added __Haunted__ to allies for the machine
Turned on "Player Trade Limit" and "Free Samples" 
Set player trade Limit to 5
Added my item and listing and then tested the "Free" feature and it gave me one sword which was set. 
(Again still didn't change the 0 of 5 times purchased.)
When trying to edit the Trader rules now it will not let me check or uncheck anything at all. 

I will post a picture of the bricked machine. I know it shows nothing but the machine looks empty but the machine had 6 full sale listing inside it before bricking. 

The second picture is of me attempting to change the Trader Rules. 
![Vending Machine Bugged](https://user-images.githubusercontent.com/77481431/191897035-25d73e40-9acf-4340-9dca-4a69275e57bf.jpg)
![won't let me select any other rule  just shows dark green check then doesn't apply it ](https://user-images.githubusercontent.com/77481431/191897043-d501c8a6-7fc9-4d48-ba49-7fb2117c02a8.jpg)

![Trader Log Vending Machine](https://user-images.githubusercontent.com/77481431/191897042-06067459-39e3-4c9c-9845-88a87078b9f3.jpg)

**Comment by Lightman314** [comment] 2022-09-23 17:23
**Questions:**

Since you asked, the "Name" input for item trades is merely an option to cosmetically change the name as displayed on the trader screen (the original item name is still listed below), allowing you to sell a branded bottle of "Moo Moo Milk" without having to waste experience naming the item in an anvil. That said, it does not actually rename the item when it gives it to the customer (with the **ONLY** exception being the Ticket Kiosk which will actually rename the printed tickets as it's unique in that it actually "makes" the item being sold from the available ticket materials in storage), it is purely a cosmetic tool that lets you effectively change the items "label" on the shelf. As for making it name the item in creative traders, there's literally no need to ever do that as if you can make a creative trader you can simply just name the item in an anvil while in creative and then set the renamed item as the item being sold.

**Issues:**
Moving on to the actual issues reported, I'm going to separate them into a checklist so I can keep track of them.

- [ ] Issue 1: From what I've read, it does appear that the trade rules are **functioning** as intended, the client just isn't receiving any update data from the server when their internal data is changed, hence why your buttons aren't updating to say 2/5 trades and isn't updating that you've already had your free sample, etc.

- [ ] Issue 2: While I don't have an exact reason why it's crashing there, when the server reloads persistent traders (which is automatically triggered when a new persistent trader is added) it forcibly resets the clients trader list, and then sends a fresh copy of all of the current traders. Considering that the crash is caused by the screen not being able to find the trader, my guess is it's trying to access the trader after the "clear client data" message was handled, but before the update data for that particular trader has been processed, resulting in the client not having a copy of that traders data and thus throwing an error. This should be somewhat fixable on my end as I can simply add some null checks on the client to make sure it doesn't crash, etc.

**Comment by Lightman314** [comment] 2022-09-23 20:30
Update: While I fixed Issue 2 easily enough (along with another few errors I found with how the Item Traders actually saved their persistent trader json data), it took me a surprisingly long time to figure out the cause of Issue 1. Fortunately I finally figured it out when adding some error catches to try and figure out the cause of another random bug I was having, and I do have to warn you to stay away from the Free Sample trade rule at all costs (until I get this update out later today), as loading the Free Sample rule from file that has **any** interactions in memory will cause an error and cause all of your Trader Data to be lost while loading from file.

**Comment by Zelioth** [comment] 2022-09-23 20:34
Hey Lightman314, Love seeing the work on the mod and I'm sorry we keep finding issues. We really want to make this mod a big part of our modpack and server to give a more balanced aspect to game play and let players not just blow through OP items willy nilly. But that being said I seem to have found another issue. 

ALL Trade Stations that were placed yesterday seem to now be empty and blank. so our server restarts once a day, each day and it seems that after the restart each of the trade stations are cleared and blank now with no owner. here is a screenshot for reference. 
![Screenshot 2022-09-23 153046](https://user-images.githubusercontent.com/77481431/192052331-04207567-14ef-42b0-97cc-3b0e2adff03f.jpg)

Also I have a question. would i be possible to make a specific debug/error log/ log report Specifically for lightmans currency. to not report ANYTHING but things like this. like report everything LC so in the case that these errors, issues, and just normal loading things happen i can submit it and it may give you more of a lead to what is going on?

**Comment by Lightman314** [comment] 2022-09-23 23:54
Should be fixed in v2.0.0.1.

**Closed by Lightman314** 2022-09-23 23:54 UTC
Labels: bug
