### ISSUE TITLE
BUG: Paygates and Ticket Machines have wrong block drops.

### ISSUE THREAD

**Issue by choombdev** [Lightman314/LightmansCurrency#98] opened 2022-10-30 01:13 UTC
Minecraft Version (REQUIRED):  1.18.2
Forge Version (REQUIRED): Latest (40.1.84)
Lightman's Currency Version (REQUIRED):  (2.0.0.3)
Other Relevant Mods & Version (LC Tech, etc.): N/A
Connection Type (Single-player, server/client, LAN world): Singleplayer
If playing on a server, was the server ever in Offline Mode: 

**Describe the bug**
Paygates are dropped twice and Ticket Machines don't drop when broken.

**To Reproduce**
1. Place a Paygate or a Ticket Machine
2. Destroy either Paygate or Ticket Machine using a PIckaxe in survival
3. Paygate is duplicated, Ticket Machine doesn't drop.

**Expected behavior**
Paygate drops once, Ticket Machine drops once.

**Screenshots/Logs/Crash Reports**

N/A

**Additional context**
No other mods were included, only Forge 40.1.84 and Lightman's Currency 2.0.0.3

**Comment by Lightman314** [comment] 2022-10-30 17:33
It would appear that I both deleted the Ticket Machine blocks loot table by accident, and somehow forgot to delete the Paygate blocks loot table on 1.18.2 (still deleted as intended on 1.19 & 1.19.2, as the Emergency Ejection system now handles the block drops of all "traders" whether they were broken legitimately or not). I should have this fixed shortly.

**Comment by Lightman314** [comment] 2022-10-30 19:27
Fixed in v2.0.0.4

**Closed by Lightman314** 2022-10-30 19:27 UTC
Labels: bug
